### ISSUE TITLE
LED - software PWM

### ISSUE THREAD

**Issue by grrrr** [electro-smith/DaisyExamples#98]
Hi, 
i am not sure whether i understand how PWM works on the daisy platform.
Looking at the SimpleLED example (https://github.com/electro-smith/DaisyExamples/tree/master/pod/SimpleLed), there is a call to hw.UpdateLeds() within the untimed infinite loop.
The speed is most probably higher than the default software "sample rate" of 1 kHz (set in libdaisy/hid/led.cpp), meaning that the LED brightness will not cover the whole analog output range. Right?
Given the abundance of PWM functionality on the STM32 platform, this should definitely be served by hardware PWM! The control of that will however change the API - i'll have to check out to which extent. Would you accept a pull request for such a change?
Connected to that is the question how/which hardware ressources are allocated by libdaisy by default. This must be well documented and/or be enabled/disabled in a modular fashion, e.g. using a global init function with HID module flags.

**Comment by stephenhensley** [comment]
Yes, you're correct. Several of the pins offer hardware PWM, and the ones that don't could definitely benefit from a better software implementation (using a dedicated timer/callback to control the LEDs independent of the Audio Callback frequency, etc.

The all-software approach was mostly done so that any GPIO could be set up as an LED without additional complexity underneath. The API could be left mostly intact, and just have a config struct (similar to I2C, etc.) for pwm specific features (if the pin supports them). 

That said, this issue would fit much better over on the libdaisy repo.
